#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("Krish %c Radha\n",3);
printf("%c + %c = %c\n",1,2,3);
printf("%10s\n","Kishore");
printf("%-10s\n","Kishore");
printf("%.3s\n","Kishore");
printf("%10.3s\n","Kishore");
printf("Bharathi address = %u\n","bharathi");
printf("Bharathi\n"+1);
printf(1+"Bharathi\n"+1);
printf("Bharathi\n"-1);
printf("Bharathi\n"+8);
printf("%d, %d, %d, %d, %d\n",'\0','\a','\b','\r',EOF);
printf("%d\n"+1,9999);
printf("%d"+1);
getch();
}
